"""Research harness — composition root that assembles all components.

This is the entry point for running the system. It:
1. Creates the main agent's tool set (injecting workspace, user_agent, dispatch_fn)
2. Constructs dispatch_fn (launches sub agent loops via run_agent_loop)
3. Manages context (system message injection per turn)
4. Runs the main agent's agentic loop
5. Collects run metrics
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pydantic

from .context import ContextManager
from .llm_client import LLMClient
from .loop import run_agent_loop
from .prompts import MAIN_AGENT_SYSTEM_PROMPT, SUB_AGENT_PROMPTS
from .runtime_env import RProbeResult, RuntimeProbeResult, probe_environment, probe_r_environment
from .schemas import AgentLoopResult, RunResult, SubAgentCompletion, TaskResult, TaskSpec
from .session_log import SessionLog
from .tools import create_main_agent_tools, create_sub_agent_tools
from .workspace import WorkspaceError

if TYPE_CHECKING:
    from .user_agent.base import UserAgent
    from .workspace import Workspace


class ResearchHarness:
    """Composition root for the multi-agent research system.

    Assembles all components and runs the main agent loop. The harness
    owns the dispatch_fn that launches sub agents, breaking the circular
    dependency between tools.py and loop.py.
    """

    # Sentinel for auto-probing R (distinct from explicit None = "disable R")
    _PROBE_R_AUTO = object()

    def __init__(
        self,
        *,
        model: str,
        workspace: Workspace,
        user_agent: UserAgent,
        llm_client: LLMClient | None = None,
        system_prompt: str | None = None,
        max_turns: int = 200,
        probe_result: RuntimeProbeResult | None = None,
        r_probe_result: RProbeResult | None | object = _PROBE_R_AUTO,
    ) -> None:
        """
        Args:
            model: Model identifier for the main agent (e.g. "gpt-4o").
            workspace: Initialized workspace instance.
            user_agent: User agent (real or simulated).
            llm_client: Optional LLM client. If None, creates one with default_model=model.
            system_prompt: Optional base system prompt. If None, uses the default
                from prompts.py.
            max_turns: Maximum LLM calls for the main agent loop.
            probe_result: Optional precomputed runtime probe. If None, the
                harness probes the runtime environment automatically.
            r_probe_result: Optional precomputed R runtime probe. If not passed
                (sentinel), the harness auto-probes R (None if Rscript not found).
                Pass None explicitly to disable R support.
        """
        self.model = model
        self.workspace = workspace
        self.user_agent = user_agent
        self.max_turns = max_turns
        self.llm_client = llm_client or LLMClient(default_model=model)
        self.context_manager = ContextManager(workspace)
        self.system_prompt = system_prompt or MAIN_AGENT_SYSTEM_PROMPT
        self.probe_result = probe_result or probe_environment()

        # R is optional — auto-probe, gracefully None if Rscript not found
        if r_probe_result is self._PROBE_R_AUTO:
            try:
                self.r_probe_result: RProbeResult | None = probe_r_environment()
            except RuntimeError:
                self.r_probe_result = None
        else:
            self.r_probe_result = r_probe_result  # type: ignore[assignment]

        self.tools = create_main_agent_tools(
            workspace,
            user_agent,
            self._dispatch_subagent,
        )
        self._session_log: SessionLog | None = None

    def run(self, initial_goal: str = "") -> RunResult:
        """Run the main agent loop.

        The first user message is generated by the SimulatedUser from its
        research brief, ensuring the opening message uses the same voice
        and persona as all subsequent user responses. The optional
        initial_goal parameter is accepted for backward compatibility but
        ignored when a SimulatedUser is configured.

        Flow:
        1. Generate initial user message from SimulatedUser (or use initial_goal fallback).
        2. Build system message (base prompt + project state summary).
        3. Run the agentic loop.
        4. Record session data and save session.json.
        5. Print terminal summary.
        6. Collect and return RunResult.

        Returns:
            RunResult with stop_reason, stage count, and usage statistics.
        """
        if self.user_agent is not None:
            initial_goal = self.user_agent.respond(
                "State your research goals and give the agent a concrete first step."
            )
        self._session_log = SessionLog(model=self.model, initial_goal=initial_goal)
        system_message = self.context_manager.build_system_message(self.system_prompt)
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": initial_goal},
        ]
        try:
            loop_result = run_agent_loop(
                llm_client=self.llm_client,
                messages=messages,
                tools=self.tools,
                max_turns=self.max_turns,
                model=self.model,
                truncate_fn=self.context_manager.truncate_tool_result,
                refresh_system_fn=lambda: self.context_manager.build_system_message(
                    self.system_prompt
                ),
                checkpoint_fn=lambda: self._save_checkpoint(messages),
                require_terminal_tool=True,
            )
        except Exception:
            self._save_crash_session(messages)
            raise

        state = self.workspace.get_state()
        stages_completed = sum(
            1
            for stage in state.stages.values()
            if stage.stage_status == "completed"
        )
        escalation_count = self._count_tool_calls(
            messages=messages,
            tool_name="escalate_to_user",
        )

        run_result = RunResult(
            stop_reason=loop_result.stop_reason,
            stages_completed=stages_completed,
            tool_call_count=loop_result.tool_call_count,
            turn_count=loop_result.turn_count,
            escalation_count=escalation_count,
            prompt_tokens=loop_result.prompt_tokens,
            completion_tokens=loop_result.completion_tokens,
            error_message=loop_result.error_message,
            final_response=loop_result.final_response,
        )

        self._session_log.record_project_state(state)
        self._session_log.record_main_conversation(messages)
        self._session_log.record_run_result(run_result)
        self._session_log.resume_history.append(
            self._build_segment_entry(
                segment_id=len(self._session_log.resume_history),
                started_at=self._session_log.started_at,
                run_result=run_result,
            )
        )
        session_path = self.workspace.root / "session.json"
        self._session_log.save(session_path)
        self._print_terminal_summary(run_result, messages, session_path)

        return run_result

    def resume(self, workspace_path: Path) -> RunResult:
        """Resume a previous run with a fresh conversation seeded from project state.

        Instead of replaying the old conversation (which may end in a bad
        state), this starts a clean agent loop in the same workspace.  The
        SimulatedUser generates a progress-aware opening message so the agent
        knows what has been completed and what to do next.

        Workspace files (data, plans, stage outputs, project_state.json) are
        the source of truth — the agent can read them via tools.  Old
        subagent_runs are carried forward so artifact provenance survives;
        per-segment counters are accumulated in `resume_history` so the
        aggregate run metrics remain correct across arbitrary resume chains;
        the prior session.json is archived to `sessions/segment_{N}.json`.

        Args:
            workspace_path: Path to the existing workspace directory
                containing project_state.json (session.json optional).

        Returns:
            RunResult covering the resumed portion of the run.
        """
        session_path = workspace_path / "session.json"
        old_session_data: dict[str, Any] | None = None
        old_run_id = "unknown"
        old_subagent_runs: list[dict[str, Any]] = []
        old_resume_history: list[dict[str, Any]] = []
        old_stop_reason: str | None = None
        old_turn_count: int | None = None

        if session_path.is_file():
            old_session_data = json.loads(session_path.read_text(encoding="utf-8"))
            old_run_id = old_session_data.get("run_id", "unknown")
            old_subagent_runs = list(old_session_data.get("subagent_runs", []))
            old_resume_history = list(old_session_data.get("resume_history", []))
            old_run_result = old_session_data.get("run_result") or {}
            old_stop_reason = old_run_result.get("stop_reason")
            old_turn_count = old_run_result.get("turn_count")

            # Migrate pre-fix sessions: no resume_history but has run_result.
            # Synthesize a single segment_0 entry so aggregation is correct.
            if not old_resume_history and old_run_result:
                old_resume_history = [
                    {
                        "segment_id": 0,
                        "started_at": old_session_data.get("started_at", ""),
                        "completed_at": old_session_data.get("completed_at", ""),
                        "stop_reason": old_run_result.get("stop_reason", "unknown"),
                        "turn_count": old_run_result.get("turn_count", 0),
                        "tool_call_count": old_run_result.get("tool_call_count", 0),
                        "escalation_count": old_run_result.get("escalation_count", 0),
                        "prompt_tokens": old_run_result.get("prompt_tokens", 0),
                        "completion_tokens": old_run_result.get("completion_tokens", 0),
                        "migrated_from_pre_fix": True,
                    }
                ]

        # Archive the prior session.json before starting a new segment.
        # segment_id of the archived segment = len(old_resume_history) - 1
        # (i.e. the most recently completed segment).
        if session_path.is_file() and old_resume_history:
            prior_segment_id = old_resume_history[-1].get("segment_id", len(old_resume_history) - 1)
            archive_dir = workspace_path / "sessions"
            archive_dir.mkdir(parents=True, exist_ok=True)
            archive_path = archive_dir / f"segment_{prior_segment_id}.json"
            if not archive_path.exists():
                archive_path.write_text(
                    session_path.read_text(encoding="utf-8"), encoding="utf-8"
                )

        # Build a progress-aware opening message from SimulatedUser.
        resume_context = self._build_resume_context()
        if self.user_agent is not None:
            initial_goal = self.user_agent.respond(resume_context)
        else:
            initial_goal = resume_context

        self._session_log = SessionLog(model=self.model, initial_goal=initial_goal)
        self._session_log.run_id = f"{old_run_id}_resumed"
        # Inject old state at START so checkpoints and crash-saves preserve it.
        self._session_log.subagent_runs = list(old_subagent_runs)
        self._session_log.resume_history = list(old_resume_history)
        self._session_log.resumed_from = {
            "run_id": old_run_id,
            "workspace_path": str(workspace_path),
            "previous_stop_reason": old_stop_reason,
            "previous_turn_count": old_turn_count,
        }

        system_message = self.context_manager.build_system_message(self.system_prompt)
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": initial_goal},
        ]

        try:
            loop_result = run_agent_loop(
                llm_client=self.llm_client,
                messages=messages,
                tools=self.tools,
                max_turns=self.max_turns,
                model=self.model,
                truncate_fn=self.context_manager.truncate_tool_result,
                refresh_system_fn=lambda: self.context_manager.build_system_message(
                    self.system_prompt
                ),
                checkpoint_fn=lambda: self._save_checkpoint(messages),
                require_terminal_tool=True,
            )
        except Exception:
            self._save_crash_session(messages)
            raise

        state = self.workspace.get_state()
        stages_completed = sum(
            1
            for stage in state.stages.values()
            if stage.stage_status == "completed"
        )
        escalation_count = self._count_tool_calls(
            messages=messages,
            tool_name="escalate_to_user",
        )

        run_result = RunResult(
            stop_reason=loop_result.stop_reason,
            stages_completed=stages_completed,
            tool_call_count=loop_result.tool_call_count,
            turn_count=loop_result.turn_count,
            escalation_count=escalation_count,
            prompt_tokens=loop_result.prompt_tokens,
            completion_tokens=loop_result.completion_tokens,
            error_message=loop_result.error_message,
            final_response=loop_result.final_response,
        )

        self._session_log.record_project_state(state)
        self._session_log.record_main_conversation(messages)
        self._session_log.record_run_result(run_result)
        self._session_log.resume_history.append(
            self._build_segment_entry(
                segment_id=len(self._session_log.resume_history),
                started_at=self._session_log.started_at,
                run_result=run_result,
            )
        )
        self._session_log.save(session_path)
        self._print_terminal_summary(run_result, messages, session_path)

        return run_result

    def _build_segment_entry(
        self,
        *,
        segment_id: int,
        started_at: datetime,
        run_result: RunResult,
    ) -> dict[str, Any]:
        """Build a resume_history entry describing a completed segment."""
        return {
            "segment_id": segment_id,
            "started_at": started_at.isoformat(),
            "completed_at": datetime.now(tz=timezone.utc).isoformat(),
            "stop_reason": run_result.stop_reason,
            "turn_count": run_result.turn_count,
            "tool_call_count": run_result.tool_call_count,
            "escalation_count": run_result.escalation_count,
            "prompt_tokens": run_result.prompt_tokens,
            "completion_tokens": run_result.completion_tokens,
        }

    def _extract_counts_from_messages(
        self, messages: list[dict[str, Any]]
    ) -> tuple[int, int]:
        """Derive (turn_count, tool_call_count) from a message list.

        Used when loop_result is unavailable (checkpoint mid-turn, crash).
        Token counts cannot be recovered from messages and remain 0 at
        checkpoint/crash time — the final save after the loop completes
        has accurate token counters.
        """
        turn_count = 0
        tool_call_count = 0
        for message in messages:
            if message.get("role") == "assistant":
                turn_count += 1
                tool_call_count += len(message.get("tool_calls") or [])
        return turn_count, tool_call_count

    def _build_resume_context(self) -> str:
        """Build a progress summary for the SimulatedUser to generate a resume message.

        Reads project_state.json and stage conclusions to produce a prompt
        that tells the SimulatedUser what has been completed and what remains.
        """
        state = self.workspace.get_state()
        lines = [
            "The previous run was interrupted. Here is what has been completed so far:"
        ]

        completed_stages = []
        incomplete_stages = []

        for stage_id in sorted(state.stages):
            stage = state.stages[stage_id]
            conclusion_path = (
                self.workspace.root / "stages" / stage_id / "conclusion.md"
            )
            if conclusion_path.is_file():
                conclusion = conclusion_path.read_text(encoding="utf-8")[:500]
                completed_stages.append((stage_id, conclusion))
            else:
                plan_path = self.workspace.root / "plans" / f"{stage_id}_plan.md"
                has_plan = plan_path.is_file()
                incomplete_stages.append((stage_id, has_plan))

        if completed_stages:
            lines.append("\nCompleted stages:")
            for stage_id, conclusion in completed_stages:
                lines.append(f"\n### {stage_id}")
                lines.append(conclusion)

        if incomplete_stages:
            lines.append("\nIncomplete stages:")
            for stage_id, has_plan in incomplete_stages:
                plan_note = " (has drafted plan)" if has_plan else ""
                lines.append(f"- {stage_id}{plan_note}")

        lines.append(
            "\nPlease review the progress and direct the agent to continue "
            "with the next incomplete stage. Be specific about what to do next."
        )

        return "\n".join(lines)

    def _save_checkpoint(self, messages: list[dict[str, Any]]) -> None:
        """Incrementally save session.json after each main-agent turn.

        Captures the current conversation and project state so that the
        session survives process kills (not just Python exceptions).
        Overwrites the previous checkpoint each turn.

        `resume_history` is NOT appended here — it only grows when a segment
        completes (successfully in run()/resume() or on crash in
        _save_crash_session). Checkpoints reflect work-in-progress only.
        """
        state = self.workspace.get_state()
        self._session_log.record_project_state(state)
        self._session_log.record_main_conversation(messages)

        # Build a partial run result with stop_reason="in_progress"
        stages_completed = sum(
            1
            for stage in state.stages.values()
            if stage.stage_status == "completed"
        )
        escalation_count = self._count_tool_calls(
            messages=messages,
            tool_name="escalate_to_user",
        )
        turn_count, tool_call_count = self._extract_counts_from_messages(messages)
        partial_result = RunResult(
            stop_reason="in_progress",  # checkpoint placeholder; final save overwrites
            stages_completed=stages_completed,
            tool_call_count=tool_call_count,
            turn_count=turn_count,
            escalation_count=escalation_count,
            prompt_tokens=0,  # live token counters live in the loop; not recoverable here
            completion_tokens=0,
        )
        self._session_log.record_run_result(partial_result)
        session_path = self.workspace.root / "session.json"
        self._session_log.save(session_path)

    def _save_crash_session(self, messages: list[dict[str, Any]]) -> None:
        """Persist session.json on unhandled exception so conversation is not lost.

        Builds a partial RunResult with stop_reason='error', appends a
        resume_history entry so aggregate metrics don't silently drop the
        crashed segment, and saves whatever state exists at crash time.
        Token counts are 0 because live counters live in the loop and
        cannot be recovered from messages alone. The active exception's
        formatted traceback is stored in error_message so post-mortem
        debugging does not depend on stdout capture.
        """
        import traceback

        crash_trace = traceback.format_exc()

        state = self.workspace.get_state()
        stages_completed = sum(
            1
            for stage in state.stages.values()
            if stage.stage_status == "completed"
        )
        escalation_count = self._count_tool_calls(
            messages=messages,
            tool_name="escalate_to_user",
        )
        turn_count, tool_call_count = self._extract_counts_from_messages(messages)
        run_result = RunResult(
            stop_reason="error",
            stages_completed=stages_completed,
            tool_call_count=tool_call_count,
            turn_count=turn_count,
            escalation_count=escalation_count,
            prompt_tokens=0,
            completion_tokens=0,
            error_message=crash_trace,
        )
        self._session_log.record_project_state(state)
        self._session_log.record_main_conversation(messages)
        self._session_log.record_run_result(run_result)
        self._session_log.resume_history.append(
            self._build_segment_entry(
                segment_id=len(self._session_log.resume_history),
                started_at=self._session_log.started_at,
                run_result=run_result,
            )
        )
        session_path = self.workspace.root / "session.json"
        self._session_log.save(session_path)
        print(
            f"\n[CRASH] Session saved to {session_path}\n"
            f"{crash_trace}",
        )

    def _dispatch_subagent(self, task_spec: TaskSpec) -> TaskResult:
        """Launch a sub agent to execute a task — the dispatch_subagent tool's backend.

        This method is bound as dispatch_fn when creating main agent tools,
        breaking the tools.py ↔ loop.py circular dependency.

        Flow:
        1. Register task in workspace (project_state update).
        2. Snapshot output files before execution.
        3. Create sub agent tool set (execution tools only, scoped to stage).
        4. Build sub agent messages with workspace manifest injected.
        5. Run an independent agentic loop (isolated messages, no main agent context).
        6. Diff output files to capture artifacts from both write_file and run_code.
        7. Write full output to workspace and return TaskResult to main agent.

        Args:
            task_spec: Full task specification from the main agent.

        Returns:
            TaskResult containing summary, artifact paths, and status.
            The main agent never sees raw code or stdout from the sub agent.
        """
        self.workspace.register_task(task_spec.stage_id, task_spec.task_id)

        # Snapshot outputs dir before sub agent runs
        outputs_dir = self.workspace.root / "stages" / task_spec.stage_id / "outputs"
        outputs_dir.mkdir(parents=True, exist_ok=True)
        files_before = _list_output_files(outputs_dir)

        sub_tools = create_sub_agent_tools(
            self.workspace,
            task_spec.stage_id,
            self.probe_result,
            self.r_probe_result,
        )
        sub_system_prompt = self._build_subagent_system_prompt(task_spec)
        workspace_manifest = self._build_workspace_manifest(task_spec.stage_id)
        task_context = (
            f"{task_spec.task_description}\n\n"
            f"## Workspace Files\n{workspace_manifest}"
        )
        sub_messages: list[dict[str, Any]] = [
            {"role": "system", "content": sub_system_prompt},
            {"role": "user", "content": task_context},
        ]
        loop_result = run_agent_loop(
            llm_client=self.llm_client,
            messages=sub_messages,
            tools=sub_tools,
            max_turns=task_spec.max_turns,
            model=self.model,
            trap_errors=True,
            require_terminal_tool=True,
            truncate_fn=self.context_manager.truncate_tool_result,
        )

        # Combine write_file artifacts + files created by run_code
        write_file_artifacts = self._extract_artifact_paths(sub_messages)
        files_after = _list_output_files(outputs_dir)
        new_files = sorted(files_after - files_before)
        run_code_artifacts = [
            f"stages/{task_spec.stage_id}/outputs/{f}" for f in new_files
        ]
        # Merge, dedup, preserve order
        all_artifacts = list(write_file_artifacts)
        for path in run_code_artifacts:
            if path not in all_artifacts:
                all_artifacts.append(path)

        completion = self._parse_subagent_completion(loop_result)
        task_result = TaskResult(
            task_id=task_spec.task_id,
            status=self._map_task_status(loop_result),
            summary=completion.summary,
            artifact_paths=all_artifacts,
            blockers=completion.blockers,
            suggestions=completion.suggestions,
            artifact_descriptions=completion.artifact_descriptions,
            error=loop_result.error_message,
        )
        self.workspace.write_task_result(
            task_spec.stage_id,
            task_spec.task_id,
            task_result,
        )
        self._update_stage_manifest(task_spec.stage_id, task_result)
        if self._session_log is not None:
            self._session_log.record_subagent_run(task_spec, sub_messages, task_result)
        return task_result

    def _update_stage_manifest(self, stage_id: str, task_result: TaskResult) -> None:
        """Aggregate artifact descriptions into stages/{stage_id}/outputs/manifest.json."""

        manifest_path = self.workspace.root / "stages" / stage_id / "outputs" / "manifest.json"
        manifest: dict[str, str] = {}
        if manifest_path.exists():
            manifest = json.loads(manifest_path.read_text())

        for path_str in task_result.artifact_paths:
            basename = Path(path_str).name
            if basename in task_result.artifact_descriptions:
                desc = task_result.artifact_descriptions[basename]
            else:
                desc = f"Output from {task_result.task_id}: {task_result.summary[:100]}"
            manifest[path_str] = desc

        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest, indent=2))

    def _build_subagent_system_prompt(self, task_spec: TaskSpec) -> str:
        """Build the sub agent system prompt from explicit override or role-based lookup.

        Assembles: base prompt + runtime environment + environment hints
        + skill index (if available in workspace).

        Priority: task_spec.system_prompt (explicit override) > validated role lookup
        in SUB_AGENT_PROMPTS.
        """

        if task_spec.system_prompt:
            base_prompt = task_spec.system_prompt
        else:
            base_prompt = SUB_AGENT_PROMPTS[task_spec.role]
        runtime_section = self._format_runtime_environment_section()
        hints_section = self._format_environment_hints()
        skill_section = self._format_skill_index()
        return (
            f"{base_prompt}\n\n{runtime_section}\n\n{hints_section}"
            + (f"\n\n{skill_section}" if skill_section else "")
        )

    def _format_runtime_environment_section(self) -> str:
        """Render the probed runtime environment for sub-agent prompts.

        Includes both Python and R sections. R section is omitted when
        Rscript is not available.
        """
        sections: list[str] = ["## Runtime Environment"]

        # Python section
        sections.append(self._format_language_section(
            header="### Python",
            interpreter_label="Python path",
            interpreter_path=self.probe_result.python_path,
            version=self.probe_result.python_version,
            available_packages=self.probe_result.available_packages,
            missing_packages=self.probe_result.missing_packages,
        ))

        # R section (only when available)
        if self.r_probe_result is not None:
            sections.append(self._format_language_section(
                header="### R",
                interpreter_label="Rscript path",
                interpreter_path=self.r_probe_result.rscript_path,
                version=self.r_probe_result.r_version,
                available_packages=self.r_probe_result.available_packages,
                missing_packages=self.r_probe_result.missing_packages,
            ))

        return "\n\n".join(sections)

    def _format_language_section(
        self,
        *,
        header: str,
        interpreter_label: str,
        interpreter_path: str,
        version: str,
        available_packages: dict[str, str],
        missing_packages: list[str],
    ) -> str:
        """Render a single language's runtime info as a Markdown section."""

        if available_packages:
            available_lines = "\n".join(
                f"- {package}=={ver}"
                for package, ver in sorted(available_packages.items())
            )
        else:
            available_lines = "- (none)"

        if missing_packages:
            missing_lines = "\n".join(
                f"- {package}" for package in sorted(missing_packages)
            )
        else:
            missing_lines = "- (none)"

        return (
            f"{header}\n\n"
            f"- {interpreter_label}: `{interpreter_path}`\n"
            f"- Version: `{version}`\n"
            "- Available packages:\n"
            f"{available_lines}\n"
            "- Missing packages:\n"
            f"{missing_lines}"
        )

    def _format_environment_hints(self) -> str:
        """Always-visible hints for common file-handling pitfalls.

        These prevent wasted turns from predictable errors (e.g. opening
        binary files as text). Injected into every sub-agent prompt.
        Includes R-specific hints when R is available.
        """
        hints = (
            "## Environment Hints\n\n"
            "- **Excel files (.xlsx)**: Use `pd.read_excel()`. Do NOT open with `open()`.\n"
            "- **MATLAB files (.mat)**: Use `scipy.io.loadmat()` to inspect variables.\n"
            "- **Large CSV/TSV**: `read_file` returns a preview. Use `pd.read_csv()` in "
            "`run_code` for full data.\n"
            "- **Encoding**: Try `encoding='utf-8-sig'` if `utf-8` fails on CSV files.\n"
            "- **Paths**: `run_code` runs in the stage outputs directory. Data files are "
            "at `../../../data/<filename>`."
        )
        if self.r_probe_result is not None:
            hints += (
                "\n\n## R Usage Notes\n\n"
                "- Set `language='r'` in run_code to execute R code.\n"
                "- Each run_code(language='r') call is **isolated** — variables and loaded "
                "libraries do NOT persist between calls.\n"
                "- Library calls for confirmed packages are **auto-prepended** — do NOT "
                "call library() yourself for packages listed in the Runtime Environment.\n"
                "- Save outputs: `write.csv()`, `ggsave()`, `saveRDS()`, `pdf()`/`dev.off()`.\n"
                "- Exchange data between Python and R via CSV files in the outputs directory.\n"
                "- Use relative filenames only (same rule as Python)."
            )
        return hints

    def _format_skill_index(self) -> str:
        """Load the skill reference index from workspace, if available.

        Returns an empty string if skills/INDEX.md doesn't exist (e.g. in
        tests or minimal workspaces).
        """
        index_path = self.workspace.root / "skills" / "INDEX.md"
        if not index_path.is_file():
            return ""
        index_content = index_path.read_text(encoding="utf-8")
        return (
            "## Skill Reference\n\n"
            "Analysis guides are available in the workspace. Browse the index below "
            "and use `read_file(\"skills/<name>/SKILL.md\")` to load a full guide "
            "when relevant to your task.\n\n"
            f"{index_content}"
        )

    def _build_workspace_manifest(self, stage_id: str) -> str:
        """Build a concise workspace file summary for subagent task context.

        The manifest exposes three pieces of state relevant to a subagent:
        - Raw data files from workspace/data/
        - Existing output artifacts for the active stage
        - Persisted task-result summaries for the active stage

        Missing or empty directories are rendered as "(none)" so the prompt
        stays explicit without failing on partially initialized workspaces.
        """

        def _format_listing(items: list[str]) -> str:
            """Render a newline-prefixed bullet list or a stable empty marker."""

            if not items:
                return "\n- (none)"
            return "".join(f"\n- {item}" for item in items)

        def _list_relative_files(directory: Path, prefix: Path) -> list[str]:
            """List files recursively under directory as prefix-relative paths."""

            if not directory.is_dir():
                return []
            return sorted(
                str(path.relative_to(prefix))
                for path in directory.rglob("*")
                if path.is_file()
            )

        data_dir = self.workspace.root / "data"
        outputs_dir = self.workspace.root / "stages" / stage_id / "outputs"
        tasks_dir = self.workspace.root / "stages" / stage_id / "tasks"

        data_files = _list_relative_files(data_dir, self.workspace.root)
        output_files = _list_relative_files(outputs_dir, self.workspace.root)

        task_summaries: list[str] = []
        if tasks_dir.is_dir():
            for result_path in sorted(tasks_dir.glob("*_result.json")):
                try:
                    task_result = TaskResult.model_validate_json(
                        result_path.read_text(encoding="utf-8")
                    )
                except (pydantic.ValidationError, ValueError) as error:
                    raise WorkspaceError(
                        f"Invalid task result file: {result_path.relative_to(self.workspace.root)}"
                    ) from error
                normalized_summary = " ".join(task_result.summary.split())
                task_summaries.append(
                    f"{task_result.task_id} [{task_result.status}]: {normalized_summary}"
                )

        return (
            "Data files:"
            f"{_format_listing(data_files)}\n\n"
            "Current stage outputs:"
            f"{_format_listing(output_files)}\n\n"
            "Completed task summaries:"
            f"{_format_listing(task_summaries)}"
        )

    def _map_task_status(self, loop_result: AgentLoopResult) -> str:
        """Map sub agent loop stop reasons into TaskResult statuses."""

        if loop_result.stop_reason == "completed":
            return "success"
        if loop_result.stop_reason == "error":
            return "failure"
        return "partial"

    def _parse_subagent_completion(self, loop_result: AgentLoopResult) -> SubAgentCompletion:
        """Parse the structured completion payload emitted by the subagent terminal tool."""

        if loop_result.stop_reason != "completed":
            return SubAgentCompletion(
                summary=loop_result.final_response or "No response from sub agent."
            )

        payload_text = loop_result.final_response or ""
        try:
            payload = json.loads(payload_text)
        except json.JSONDecodeError as error:
            raise ValueError(
                "Subagent terminal tool returned invalid completion payload."
            ) from error

        return SubAgentCompletion.model_validate(payload)

    def _extract_artifact_paths(self, messages: list[dict[str, Any]]) -> list[str]:
        """Extract write_file artifact paths from the sub agent conversation."""

        write_file_call_ids: set[str] = set()
        artifact_paths: list[str] = []

        for message in messages:
            for tool_call in message.get("tool_calls", []):
                function_data = tool_call.get("function", {})
                if function_data.get("name") == "write_file":
                    tool_call_id = tool_call.get("id")
                    if isinstance(tool_call_id, str):
                        write_file_call_ids.add(tool_call_id)

            tool_call_id = message.get("tool_call_id")
            content = message.get("content")
            if (
                message.get("role") == "tool"
                and isinstance(tool_call_id, str)
                and tool_call_id in write_file_call_ids
                and isinstance(content, str)
                and content.startswith("File written: ")
            ):
                artifact_path = content.removeprefix("File written: ").strip()
                if artifact_path and artifact_path not in artifact_paths:
                    artifact_paths.append(artifact_path)

        return artifact_paths

    def _count_tool_calls(
        self,
        *,
        messages: list[dict[str, Any]],
        tool_name: str,
    ) -> int:
        """Count assistant tool calls by function name across a conversation."""

        count = 0
        for message in messages:
            for tool_call in message.get("tool_calls", []):
                function_data = tool_call.get("function", {})
                if function_data.get("name") == tool_name:
                    count += 1
        return count

    def _collect_tool_counts(self, messages: list[dict[str, Any]]) -> Counter[str]:
        """Collect per-tool call counts from the main agent conversation."""
        counts: Counter[str] = Counter()
        for message in messages:
            for tool_call in message.get("tool_calls", []):
                function_data = tool_call.get("function", {})
                name = function_data.get("name")
                if name:
                    counts[name] += 1
        return counts

    def _print_terminal_summary(
        self,
        run_result: RunResult,
        messages: list[dict[str, Any]],
        session_path: Path,
    ) -> None:
        """Print a compact run summary to stdout after the run completes."""
        import sys

        tool_counts = self._collect_tool_counts(messages)
        tool_breakdown = ", ".join(
            f"{name}x{count}" for name, count in tool_counts.most_common()
        )

        border = "─" * 56
        lines = [
            f"╭─ Run Complete {border[:42]}╮",
            f"│ Stop reason: {run_result.stop_reason:<42}│",
            f"│ Stages:      {run_result.stages_completed} completed{' ' * 32}│",
            f"│ Tool calls:  {run_result.tool_call_count:<42}│",
        ]
        if tool_breakdown:
            # Wrap long breakdowns
            remaining = tool_breakdown
            first = True
            while remaining:
                chunk = remaining[:42]
                remaining = remaining[42:]
                if first:
                    lines.append(f"│              ({chunk:<41}│")
                    first = False
                else:
                    lines.append(f"│               {chunk:<41}│")
            # Close last paren if needed
            if ")" not in lines[-1]:
                lines[-1] = lines[-1].rstrip("│").rstrip() + ")" + " " * 5 + "│"
        lines.extend(
            [
                f"│ Escalations: {run_result.escalation_count:<42}│",
                f"│ Tokens:      {run_result.prompt_tokens} prompt + "
                f"{run_result.completion_tokens} completion"
                f"{' ' * max(0, 42 - len(str(run_result.prompt_tokens)) - len(str(run_result.completion_tokens)) - 22)}│",
                f"│ Session log: {str(session_path):<42}│",
                f"╰{border}╯",
            ]
        )
        print("\n".join(lines), file=sys.stderr)


def _list_output_files(directory: Path) -> set[str]:
    """Return all files under directory as directory-relative paths."""

    if not directory.is_dir():
        return set()
    return {
        str(path.relative_to(directory))
        for path in directory.rglob("*")
        if path.is_file()
    }


def _deserialize_conversation(
    serialized: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Convert session.json's serialized conversation back to live message format.

    Session.json serializes tool_calls as:
        {"id": "...", "name": "...", "arguments": {...}}

    The live loop format (matching litellm/OpenAI) expects:
        {"id": "...", "type": "function", "function": {"name": "...", "arguments": "<json-string>"}}

    This function converts the serialized format back so the loop can
    continue appending new messages in the correct format.
    """
    messages: list[dict[str, Any]] = []
    for msg in serialized:
        entry: dict[str, Any] = {"role": msg["role"]}

        if msg.get("content") is not None:
            entry["content"] = msg["content"]

        if msg.get("tool_call_id") is not None:
            entry["tool_call_id"] = msg["tool_call_id"]

        if "tool_calls" in msg:
            entry["tool_calls"] = [
                {
                    "id": tc["id"],
                    "type": "function",
                    "function": {
                        "name": tc["name"],
                        "arguments": json.dumps(tc["arguments"]),
                    },
                }
                for tc in msg["tool_calls"]
            ]

        messages.append(entry)
    return messages


def _extract_simulated_user_history(
    conversation: list[dict[str, Any]],
    system_message: dict[str, str],
) -> list[dict[str, str]]:
    """Reconstruct SimulatedUser's conversation_history from escalation exchanges.

    The SimulatedUser's conversation_history is structured as:
        [system_message, user_msg_1, assistant_msg_1, user_msg_2, assistant_msg_2, ...]

    Where each (user, assistant) pair corresponds to one escalate_to_user call:
    - user = the "summary" argument passed to escalate_to_user
    - assistant = the tool result (the simulated user's response)

    This function scans the serialized main conversation for escalate_to_user
    tool calls and their corresponding tool results, rebuilding the history.

    Args:
        conversation: Serialized main_conversation from session.json.
        system_message: The SimulatedUser's system message (constructed
            at init time from the research brief).

    Returns:
        Reconstructed conversation_history list suitable for
        SimulatedUser.restore_history().
    """
    history: list[dict[str, str]] = [system_message]

    # Build a map: tool_call_id -> summary text (from escalate_to_user calls)
    escalation_calls: dict[str, str] = {}
    for msg in conversation:
        for tc in msg.get("tool_calls", []):
            if tc.get("name") == "escalate_to_user":
                args = tc.get("arguments", {})
                summary = args.get("summary", "")
                call_id = tc.get("id")
                if call_id:
                    escalation_calls[call_id] = summary

    # Match tool results to escalation calls, preserving conversation order
    for msg in conversation:
        if msg.get("role") != "tool":
            continue
        call_id = msg.get("tool_call_id")
        if call_id in escalation_calls:
            # user turn = the summary the main agent sent
            history.append({"role": "user", "content": escalation_calls[call_id]})
            # assistant turn = the simulated user's response
            history.append({"role": "assistant", "content": msg.get("content", "")})

    return history
